[tool.poetry]
name = "ai-worker"
version = "0.1.0"
description = "api server that posts capabilities, and accepts jobs"
authors = ["erik aronesty <erik@q32.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "ai_worker"}]

[tool.poetry.dependencies]
python = "^3.11"
llama-cpp-python = {extras = ["server"], version = "^0.1.83"}
pydantic-settings = "^2.0.3"
fastapi = "^0.103.1"
sseclient = "^0.0.27"
websockets = "^11.0.3"
httpx = "^0.24.1"
psutil = "^5.9.5"
huggingface-hub = "^0.16.4"
sentencepiece = "^0.1.99"
python-dotenv = "^1.0.0"
boto3 = "^1.28.43"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
